model: AttentionSeq2Seq
model_params:
  attention.class: seq2seq.decoders.attention.AttentionLayerBahdanau
  attention.params:
    num_units: 512
  bridge.class: seq2seq.models.bridges.InitialStateBridge
  embedding.dim: 512
  encoder.class: seq2seq.encoders.BidirectionalRNNEncoder
  encoder.params:
    rnn_cell:
      cell_class: LSTMCell
      residual_connections: True
      cell_params:
        num_units: 512
      dropout_input_keep_prob: 0.7
      dropout_output_keep_prob: 1.0
      num_layers: 3
  decoder.class: seq2seq.decoders.AttentionDecoder
  decoder.params:
    rnn_cell:
      cell_class: LSTMCell
      cell_params:
        num_units: 512
      dropout_input_keep_prob: 0.7
      dropout_output_keep_prob: 1.0
      num_layers: 3
  optimizer.name: Adam
  optimizer.params:
    epsilon: 0.0000008
  optimizer.learning_rate: 0.0001
  source.max_seq_len: 100
  source.reverse: false
  target.max_seq_len: 100